# syntax=docker/dockerfile:1
# Define la versión de la sintaxis de Dockerfile que se utilizará

FROM alpine
# Especifica la imagen base del contenedor
# Alpine es una distribución de Linux ligera y muy utilizada en Docker

RUN echo "Hello world!"
# Ejecuta un comando durante la construcción de la imagen
# Este comando imprime el mensaje "Hello world!" en la consola